name: Build Native

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config \
          libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev \
          libboost-chrono-dev libboost-program-options-dev libboost-test-dev \
          libboost-thread-dev libdb++-dev libsqlite3-dev

      - name: Build
        run: |
          ./autogen.sh
          # Tambahkan flag --disable-wallet dan --disable-zmq agar tidak mencari libdb/zmq
          ./configure --disable-wallet --disable-zmq --disable-tests --disable-bench CXXFLAGS="-std=c++14"
          make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: termucoin-native
          path: src/termucoind
